variable "subnet_ids" {}
variable "family" {}
variable "allocated_storage" {}
variable "storage_type" {}
variable "engine" {}
variable "engine_version" {}
variable "instance_class" {}
variable "component" {}
variable "env" {}
variable "vpc_id" {}
variable "server_app_port_sg_cidr" {}
variable "skip_final_snapshot" {}